# Generated by Django 5.2.7 on 2025-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menuapp.category'),
        ),
    ]
