# Generated by Django 5.2.7 on 2025-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_remove_menuitem_category_menuitem_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
