# Generated by Django 5.2.7 on 2025-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_menuitem_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='manual_categories',
            field=models.ManyToManyField(blank=True, related_name='manual_menu_items', to='menuapp.category'),
        ),
    ]
