# Generated by Django 5.2.7 on 2025-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_manualcategory_alter_menuitem_manual_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
