# Generated by Django 5.2.7 on 2025-10-19 10:14

import menuapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0006_alter_menuitem_image_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to=menuapp.models.MenuItem.hotel_image_upload_path),
        ),
    ]
